version: '3.0.0'
systemName: 'OpenStack VPS & Cloud'
description: 'Introduce automatic provisioning of flexible VPS products in WHMCS and allow your clients to conveniently manage their virtual servers remotely. <br>For more info visit our <a href="https://www.docs.modulesgarden.com/OpenStack_VPS_And_Cloud_For_WHMCS" style="color: #4169E1;" target="_blank">Wiki</a>.'
clientAreaName: 'OpenStack VPS & Cloud'
adminAreaName: 'OpenStack VPS & Cloud'
clientAreaController: Home
adminAreaController: Dashboard
author: '<a href="https://www.modulesgarden.com" target="_blank">ModulesGarden</a>'
moduleIcon: 'openstack_vps'
debug: false
#fields: https://developers.whmcs.com/addon-modules/configuration/
#  option1:
#    FriendlyName: XXX
#    Type: text