<?php
/*
 * File generated by ModulesGarden packages system
 * 
 * Below you can find current version & revision of this module
 */

$moduleVersion = '3.0.0-t136152v3';
$moduleRevision = 'e7c16c58f40d0c3a5ac551784d160c12a2c7f0d2';
$moduleWikiUrl = 'https://www.docs.modulesgarden.com/OpenStack_VPS_And_Cloud_For_WHMCS';