dashboard:
  icon: 'home'
appCenter:
tools:
  icon: 'wrench'
  submenu:
    queue: [ ]
    logs: [ ]
    mediaLibrary: [ ]
    easyTranslator: [ ]
documentation:
  icon: 'file-document'
  externalUrl: 'https://www.docs.modulesgarden.com/OpenStack_VPS_And_Cloud_For_WHMCS'
  target: '_black'
queue:
  hide: true
logs:
  hide: true
easyTranslator:
  hide: true
mediaLibrary:
  hide: true