<?php

//table
$_LANG['packages.product.modals.create_configurable_options.title'] = 'Create Configurable Options';
$_LANG['packages.product.modals.create_configurable_options.configurableOptionsNameInfo'] = 'Below you can choose which configurable options will be generated for this product. Please note that these options are divided into two parts separated by a | sign, where the part on the left indicates the sent variable and the part on the right the friendly name displayed to customers. After generating these options you can edit the friendly part on the right, but not the variable part on the left. More information about configurable options and their editing can be found <a class="lu-font-weight-bold" href=":configurableOptionsNameUrl" target="_blank">here</a>.';

$_LANG['packages.product.services.configurable_options_group_service.autoGenerateGroupName']        = 'Configurable options for :productName product';
$_LANG['packages.product.services.configurable_options_group_service.autoGenerateGroupDescription'] = 'Auto generated by module :moduleName';
$_LANG['packages.product.services.configurable_options_group.autoGenerateGroupName']                = 'Configurable options for :productName product';
$_LANG['packages.product.services.configurable_options_group.autoGenerateGroupDescription']         = 'Auto generated by module :moduleName';
$_LANG['packages.product.providers.create_configurable_options.create_success']                     = 'Configurable options created successfully';

$_LANG['packages.product.product_configuration.form.title']                          = 'Configurable Options';
$_LANG['packages.product.product_configuration.form.button_submit']                  = 'Create Configurable Options';

$_LANG['packages.product.errors.productRequiresServer']             = 'Selected product requires server.';
$_LANG['packages.product.errors.invalidServerType']                 = 'Selected server type is invalid, please select a proper server group with the ":moduleName" servers in order to proceed.';

$_LANG['packages.product.buttons.server_configuration.button.title']              = 'Configure';
$_LANG['packages.product.modals.server_configuration.modal.title']                = 'Configure Server';
$_LANG['packages.product.providers.server_configuration.create_success']          = 'Server configuration has been saved successfully.';
$_LANG['packages.product.alerts.server_configuration_alert.finish_configuration'] = 'Switch to Advanced Mode to complete the server configuration.';

//Hostname Generate Widget
$_LANG['packages.product.widgets.hostname_generate_widget.title']                                            = 'Hostname Generation';
$_LANG['packages.product.forms.hostname_generate_form.customconfigoption[hostnameFormat]']                   = 'Hostname Format';
$_LANG['packages.product.forms.hostname_generate_form.customconfigoption[hostnameFormat]_description']       = 'Define the pattern used to generate the hostname automatically. You can use following variables: {$whmcsMainDomain}, {$clientId}, {$serviceId}, {$orderId}, {$rand}, and {$nextIncrementalValue}.';
$_LANG['packages.product.forms.hostname_generate_form.customconfigoption[overrideDomain]']                   = 'Override Domain';
$_LANG['packages.product.forms.hostname_generate_form.customconfigoption[overrideDomain]_description']       = 'Enable to generate a hostname even when a domain is already set.';
$_LANG['packages.product.forms.hostname_generate_form.customconfigoption[nextIncrementalValue]']             = 'Next Incremental Value';
$_LANG['packages.product.forms.hostname_generate_form.customconfigoption[nextIncrementalValue]_description'] = 'Used in the {$nextIncrementalValue} tag. This number increases automatically each time a hostname is generated.';
$_LANG['packages.product.forms.hostname_generate_form.customconfigoption[randomChars]']                      = 'Random Character Set';
$_LANG['packages.product.forms.hostname_generate_form.customconfigoption[randomChars]_description']          = 'Define the pool of characters used to generate the {$rand} value in the Hostname Format. Leave empty to use the default character set.';
$_LANG['packages.product.forms.hostname_generate_form.customconfigoption[randomLength]']                     = 'Random Value Length';
$_LANG['packages.product.forms.hostname_generate_form.customconfigoption[randomLength]_description']         = 'Set the number of characters for the {$rand} value in the Hostname Format. Leave empty or set to 0 to use the default length.';
