ALTER TABLE `#prefix#Job` ADD COLUMN `queue` VARCHAR(32) DEFAULT 'default';
ALTER TABLE `#prefix#Job` ADD COLUMN `rel_custom` VARCHAR(32) DEFAULT NULL;
ALTER TABLE `#prefix#Job` MODIFY COLUMN `id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT;
ALTER TABLE `#prefix#Job` MODIFY COLUMN `updated_at` DATETIME DEFAULT NULL;
ALTER TABLE `#prefix#Job` MODIFY COLUMN `parent_id` INT(11) UNSIGNED DEFAULT NULL;
ALTER TABLE `#prefix#Job` MODIFY COLUMN `rel_id` INT(11) UNSIGNED DEFAULT NULL;
ALTER TABLE `#prefix#Job` DROP INDEX `rel_type`;
ALTER TABLE `#prefix#Job` DROP INDEX `status`;
ALTER TABLE `#prefix#Job` DROP COLUMN `custom_id`;